### PR TITLE
Fix npm's deployment path

### PR DESCRIPTION
**Pull request by connyay**
Fixes https://github.com/jfrog/jfrog-cli/issues/2280

- [x] All [tests](https://github.com/jfrog/build-info-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/build-info-go/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

### CODE REVIEW

**Comment by connyay** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sverdlov93** [comment]
Hi @connyay, following the above fix do you think that the artifact name should include the scope also?
image

**Comment by sverdlov93** [comment]
> Hi @connyay, following the above fix do you think that the artifact name should also include the scope? image because currently its uploaded without it . jfrog-cli-tests-=1.0.0.tgz > @scope/jfrog-cli-tests-=1.0.0.tgz

@connyay

**Comment by connyay** [comment]
@sverdlov93 I am not sure. I don't think so. 

This test case matches my expectations:
https://github.com/jfrog/build-info-go/blob/c694d21943a912be849aada274dc0cc82cabdabc/build/utils/npm_test.go#L102

From what I can tell this change will fix https://github.com/jfrog/jfrog-cli/issues/2280

Is there a separate issue about the artifact name not having scope?

**Comment by sverdlov93** [comment]
Following your change, we have failing tests on JFrog CLI, so I am trying to understand how to handle that.
For example:
{
  "name": "@my-scope/my-package",
  "version": "1.0.0",
  "description": "A sample scoped package",
}
The artifact name here should be @my-scope/my-package or my-package ?

**Pull request merged**
